export const initialState = {
    photos: {},
};



export const QUERY_PHOTOS_LIST = 'QUERY_PHOTOS_LIST'
export const QUERY_PHOTOS_LIST_SUCCESSFUL = 'QUERY_PHOTOS_LIST_SUCCESSFUL'
export const QUERY_PHOTOS_LIST_FAILED = 'QUERY_PHOTOS_LIST_FAILED'

export const QUERY_PETS_LIST = 'QUERY_PETS_LIST'
export const QUERY_PETS_LIST_SUCCESSFUL = 'QUERY_PETS_LIST_SUCCESSFUL'
export const QUERY_PETS_LIST_FAILED = 'QUERY_PETS_LIST_FAILED'

